### ISSUE TITLE
ch5-17: Missing files/not matching chapter

### ISSUE THREAD

**Issue by chris2shehu** [bcafferky/masterazuredatabrickssbs#1]
5-17 want's you to describe the factinternetsalesreason table. Looking at the Chapter_05/data directory there isn't a a file for this table. The closest is factinternetsales but those are probably different? DimSalesReason is also missing and produces errors due to no schema being detected(Since it doesn't exists)

**Comment by chris2shehu** [comment]
Several other tables referenced in the prebuilt notebook are also missing. You can tell because they generate an error stating that the schema can't be confirmed.

**Comment by bcafferky** [comment]
> 5-17 want's you to describe the factinternetsalesreason table. Looking at the Chapter_05/data directory there isn't a a file for this table. The closest is factinternetsales but those are probably different? DimSalesReason is also missing and produces errors due to no schema being detected(Since it doesn't exists)

Hi Chris, Did you buy the book?

**Comment by chris2shehu** [comment]
Yes I brought the kindle version and have been enjoying it. I somehow missed widgets altogether during my own studies so it's been very useful. 

> > 5-17 want's you to describe the factinternetsalesreason table. Looking at the Chapter_05/data directory there isn't a a file for this table. The closest is factinternetsales but those are probably different? DimSalesReason is also missing and produces errors due to no schema being detected(Since it doesn't exists)
> 
> Hi Chris, Did you buy the book?

![missingfiles](https://user-images.githubusercontent.com/18371644/116013243-0f7b9b80-a5fd-11eb-8283-e152652dc2ba.jpg)

Yes, I bought the kindle version. I attached a screenshot of where I'm seeing the reference to the missing files.

**Comment by bcafferky** [comment]
> Yes I brought the kindle version and have been enjoying it. I somehow missed widgets altogether during my own studies so it's been very useful.
> 
> > > 5-17 want's you to describe the factinternetsalesreason table. Looking at the Chapter_05/data directory there isn't a a file for this table. The closest is factinternetsales but those are probably different? DimSalesReason is also missing and produces errors due to no schema being detected(Since it doesn't exists)
> > 
> > 
> > Hi Chris, Did you buy the book?
> 
> ![missingfiles](https://user-images.githubusercontent.com/18371644/116013243-0f7b9b80-a5fd-11eb-8283-e152652dc2ba.jpg)
> 
> Yes, I bought the kindle version. I attached a screenshot of where I'm seeing the reference to the missing files.

Ok.  Thanks and glad to see you are working through the examples. And Doh!  I did miss adding those two files but just did it now.  Thanks and please confirm all is working now.

Thanks for pointing this out.  I'm a bit surprised no one else hit this yet.

**Comment by chris2shehu** [comment]
That worked Thanks!
